[package]
name = "image-effect"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["console"] }
base64 = "0.21"
image = { version = "0.24", default-features = false, features = ["png"] }